/**
 * English defaults for widget `labels` (bundled; merged with lazy locale + API + options).
 */
export const defaultLabels = {
  poweredBy: "Powered by",
  inputPlaceholder: "Send a message...",
  firstMessage: "What can I help you with?",
  sources: "Sources",
  helpful: "Rate as helpful",
  unhelpful: "Rate as unhelpful",
  getSupport: "Contact support",
  floatingButton: "Help",
  suggestions: "Not sure what to ask?",
  close: "Close",
  create: "Create your own!",
  submit: "Submit",
  cancel: "Cancel",
  rateLimitMessage:
    "You are sending messages too fast. Please slow down.",
  leadCollectMessage:
    "Before we continue, could you share a few details?",
  requiredField: "Please fill out required fields.",
  continue: "Continue",
  leadCollectEmpty: "No fields configured.",
  selectOption: "Select an option",
  feedbackMessage: "Was this answer helpful?",
  feedbackYes: "Yes",
  feedbackNo: "No",
  resetChat: "Reset conversation",
  footerMessage: "",
  copyResponse: "Copy response",
  copied: "Copied!",
  agentActivityThinking: "Thinking…",
  agentActivityTool: "Working…",
  agentActivitySearchDocumentation: "Searching documentation…",
  agentActivityWebSearch: "Searching the web…",
  agentActivityWebSearchQuery: "Searching web for {query}",
  agentActivityWebSearchOpeningPage: "Opening {url}",
  agentActivityWebSearchSearchingPage: "Searching page for {pattern}",
  agentActivityCodeInterpreter: "Running code…",
  agentActivityStripeRecentInvoices: "Fetching recent invoices…",
  agentActivityStripeCustomerSubscriptions: "Fetching subscriptions…",
  agentActivityStripeBillingPortal: "Creating billing portal link…",
  agentActivityStripeRefundLatestPayment: "Processing refund…",
  agentActivityStripeCancelSubscription: "Processing cancellation…",
  bookingStatusBooked: "Booked",
  bookingStatusRescheduled: "Rescheduled",
  bookingSummaryEvent: "Event",
  bookingSummaryStarts: "Starts",
  bookingSummaryEnds: "Ends",
  stripeAmount: "Amount",
  stripeInvoice: "Invoice",
  stripeAmountDue: "Due",
  stripeAmountPaid: "Paid",
  stripeDate: "Date",
  stripeViewInvoice: "View Invoice",
  stripeHideLineItems: "Hide line items",
  stripeViewLineItems: "View {count} line item(s)",
  stripeItem: "Item",
  stripeQty: "Qty",
  stripeSubscription: "Subscription",
  stripeCurrentPeriod: "Current Period",
  stripeTrialEnds: "Trial Ends",
  stripeTrialDayLeft: "day left",
  stripeTrialDaysLeft: "days left",
  stripeCancelsAtPeriodEnd: "Cancels at end of billing period",
  stripeIntervalDay: "day",
  stripeIntervalWeek: "week",
  stripeIntervalMonth: "month",
  stripeIntervalYear: "year",
  stripeIntervalDays: "days",
  stripeIntervalWeeks: "weeks",
  stripeIntervalMonths: "months",
  stripeIntervalYears: "years",
  stripeStatusDraft: "Draft",
  stripeStatusOpen: "Open",
  stripeStatusPaid: "Paid",
  stripeStatusUncollectible: "Uncollectible",
  stripeStatusVoid: "Void",
  stripeStatusIncomplete: "Incomplete",
  stripeStatusIncompleteExpired: "Incomplete expired",
  stripeStatusTrialing: "Trialing",
  stripeStatusActive: "Active",
  stripeStatusPastDue: "Past due",
  stripeStatusPastDueUnresolved: "Past due (unresolved)",
  stripeStatusCanceled: "Canceled",
  stripeStatusUnpaid: "Unpaid",
  stripeStatusPaused: "Paused",
};

export const DEFAULT_LABEL_KEYS = Object.freeze(Object.keys(defaultLabels));
